version: '2.0'

services:
  wp-web:
   image: nginx:latest
   container_name: wp-web
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - ./code:/code
     - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf
     - ./config/nginx/snippets:/etc/nginx/snippets/
     - ./ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
     - ./ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
     - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem 
  php-fpm:
   container_name: php7-fpm
   build: ./dockerfiles/php-fpm
   volumes:
     - ./code:/code
     - ./config/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
   environment:
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_PORT=${MYSQL_PORT}
  wp-db:
   container_name: wp-db
   build: ./dockerfiles/wp-db
   volumes:
     - "./data/.data/db:/var/lib/mysql"
     - "./backup:/backup"
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
